version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: students_postgres
    restart: always
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

volumes:
  postgres_data:
